CFLAGS=-Wall -g
CSHARED=-fPIC -shared

all: 0344 1323 0136 0169 0283 0013 0202 0204 0242 0371 0326 $\
 0191 0231 0342 0007 0263 0461 0069 0367 0762 0476 1009 0693 $\
 0190 1464 0961 0201 1486 1491 0509 0965 1550 1010 0009 1523 $\
 1137 1287 0387

0344:
	gcc $(CSHARED) -o 0344-reverse-string/reverse-string.so 0344-reverse-string/0344.c
1323:
	gcc $(CSHARED) -o 1323-maximum-69-number/maximum-69-number.so 1323-maximum-69-number/1323.c
0136:
	gcc $(CSHARED) -o 0136-single-number/single-number.so 0136-single-number/0136.c
0169:
	gcc $(CSHARED) -o 0169-majority-element/majority-element.so 0169-majority-element/0169.c
0283:
	gcc $(CSHARED) -o 0283-move-zeroes/move-zeroes.so 0283-move-zeroes/0283.c
0013:
	gcc $(CSHARED) -o 0013-roman-to-integer/roman-to-integer.so 0013-roman-to-integer/0013.c
0202:
	gcc $(CSHARED) -o 0202-happy-number/happy-number.so 0202-happy-number/0202.c
0204:
	gcc $(CSHARED) -o 0204-count-primes/count-primes.so 0204-count-primes/0204.c
0242:
	gcc $(CSHARED) -o 0242-valid-anagram/valid-anagram.so 0242-valid-anagram/0242.c
0371:
	gcc $(CSHARED) -o 0371-sum-two-integers/sum-two-integers.so 0371-sum-two-integers/0371.c
0326:
	gcc $(CSHARED) -o 0326-power-of-three/power-of-three.so 0326-power-of-three/0326.c
0191:
	gcc $(CSHARED) -o 0191-number-1-bits/number-1-bits.so 0191-number-1-bits/0191.c
0231:
	gcc $(CSHARED) -o 0231-power-of-two/power-of-two.so 0231-power-of-two/0231.c
0342:
	gcc $(CSHARED) -o 0342-power-of-four/power-of-four.so 0342-power-of-four/0342.c
0007:
	gcc $(CSHARED) -o 0007-reverse-integer/reverse-integer.so 0007-reverse-integer/0007.c
0263:
	gcc $(CSHARED) -o 0263-ugly-number/ugly-number.so 0263-ugly-number/0263.c
0461:
	gcc $(CSHARED) -o 0461-hamming-distance/hamming-distance.so 0461-hamming-distance/0461.c
0069:
	gcc $(CSHARED) -o 0069-sqrt/sqrt.so 0069-sqrt/0069.c
0367:
	gcc $(CSHARED) -o 0367-valid-perfect-square/valid-perfect-square.so 0367-valid-perfect-square/0367.c
0762:
	gcc $(CSHARED) -o 0762-count-prime-bits/count-prime-bits.so 0762-count-prime-bits/0762.c
0476:
	gcc $(CSHARED) -o 0476-number-complement/number-complement.so 0476-number-complement/0476.c
1009:
	gcc $(CSHARED) -o 1009-complement-base-10/complement-base-10.so 1009-complement-base-10/1009.c
0693:
	gcc $(CSHARED) -o 0693-alternating-bits/alternating-bits.so 0693-alternating-bits/0693.c
0190:
	gcc $(CSHARED) -o 0190-reverse-bits/reverse-bits.so 0190-reverse-bits/0190.c
1464:
	gcc $(CSHARED) -o 1464-max-product/max-product.so 1464-max-product/1464.c
0961:
	gcc $(CSHARED) -o 0961-repeated-element/repeated-element.so 0961-repeated-element/0961.c
0201:
	gcc $(CSHARED) -o 0201-bitwise-and/bitwise-and.so 0201-bitwise-and/0201.c
1486:
	gcc $(CSHARED) -o 1486-xor-array/xor-array.so 1486-xor-array/1486.c
1491:
	gcc $(CSHARED) -o 1491-average-salary/average-salary.so 1491-average-salary/1491.c
0509:
	gcc $(CSHARED) -o 0509-fibonacci-number/fibonacci-number.so 0509-fibonacci-number/0509.c
0965:
	gcc $(CSHARED) -o 0965-univalued-binary-tree/univalued-binary-tree.so 0965-univalued-binary-tree/0965.c
1550:
	gcc $(CSHARED) -o 1550-consecutive-odd/consecutive-odd.so 1550-consecutive-odd/1550.c
1010:
	gcc $(CSHARED) -o 1010-divisible-pairs/divisible-pairs.so 1010-divisible-pairs/1010.c
0009:
	gcc $(CSHARED) -o 0009-palindrome-number/palindrome-number.so 0009-palindrome-number/0009.c
1523:
	gcc $(CSHARED) -o 1523-count-odd/count-odd.so 1523-count-odd/1523.c
1137:
	gcc $(CSHARED) -o 1137-tribonacci/tribonacci.so 1137-tribonacci/1137.c
1287:
	gcc $(CSHARED) -o 1287-elem-appearing/elem-appearing.so 1287-elem-appearing/1287.c
0387:
	gcc $(CSHARED) -o 0387-unique-character/unique-character.so 0387-unique-character/0387.c
clean:
	rm -f 0344-reverse-string/reverse-string.so
	rm -f 1323-maximum-69-number/maximum-69-number.so
	rm -f 0136-single-number/single-number.so
	rm -f 0169-majority-element/majority-element.so
	rm -f 0283-move-zeroes/move-zeroes.so
	rm -f 0013-roman-to-integer/roman-to-integer.so
	rm -f 0202-happy-number/happy-number.so
	rm -f 0204-count-primes/count-primes.so
	rm -f 0242-valid-anagram/valid-anagram.so
	rm -f 0371-sum-two-integers/sum-two-integers.so
	rm -f 0326-power-of-three/power-of-three.so
	rm -f 0191-number-1-bits/number-1-bits.so
	rm -f 0231-power-of-two/power-of-two.so
	rm -f 0342-power-of-four/power-of-four.so
	rm -f 0007-reverse-integer/reverse-integer.so
	rm -f 0263-ugly-number/ugly-number.so
	rm -f 0461-hamming-distance/hamming-distance.so
	rm -f 0069-sqrt/sqrt.so
	rm -f 0367-valid-perfect-square/valid-perfect-square.so
	rm -f 0762-count-prime-bits/count-prime-bits.so
	rm -f 0476-number-complement/number-complement.so
	rm -f 1009-complemet-base-10/complement-base-10.so
	rm -f 0693-alternating-bits/alternating-bits.so
	rm -f 0190-reverse-bits/reverse-bits.so
	rm -f 1464-max-product/max-product.so
	rm -f 0961-repeated-element/repeated-element.so
	rm -f 0201-bitwise-and/bitwise-and.so
	rm -f 1486-xor-array/xor-array.so
	rm -f 1491-average-salary/average-salary.so
	rm -f 0509-fibonacci-number/fibonacci-number.so
	rm -f 0965-univalued-binary-tree/univalued-binary-tree.so
	rm -f 1550-consecutive-odd/consecutive-odd.so
	rm -f 1010-divisible-pairs/divisible-pairs.so
	rm -f 0009-palindrome-number/palindrome-number.so
	rm -f 1523-count-odd/count-odd.so
	rm -f 1137-tribonacci/tribonacci.so
	rm -f 1287-elem-appearing/elem-appearing.so
	rm -f 0387-unique-character/unique-character.so
