CFLAGS=-Wall -g
CSHARED=-fPIC -shared

all: 0344 1323

0344:
	gcc $(CSHARED) -o 0344-reverse-string/reverse-string.so 0344-reverse-string/0344.c
1323:
	gcc $(CSHARED) -o 1323-maximum-69-number/maximum-69-number.so 1323-maximum-69-number/1323.c
clean:
	rm -f 0344-reverse-string/reverse-string.so
	rm -f 1323-maximum-69-number/maximum-69-number.so
