CFLAGS=-Wall -g
CSHARED=-fPIC -shared

all: 0344 1323 0136 0169 0283 0013 0202 0204 0242 0371 0326 $\
 0191 0231 0342 0007 0263 0461

0344:
	gcc $(CSHARED) -o 0344-reverse-string/reverse-string.so 0344-reverse-string/0344.c
1323:
	gcc $(CSHARED) -o 1323-maximum-69-number/maximum-69-number.so 1323-maximum-69-number/1323.c
0136:
	gcc $(CSHARED) -o 0136-single-number/single-number.so 0136-single-number/0136.c
0169:
	gcc $(CSHARED) -o 0169-majority-element/majority-element.so 0169-majority-element/0169.c
0283:
	gcc $(CSHARED) -o 0283-move-zeroes/move-zeroes.so 0283-move-zeroes/0283.c
0013:
	gcc $(CSHARED) -o 0013-roman-to-integer/roman-to-integer.so 0013-roman-to-integer/0013.c
0202:
	gcc $(CSHARED) -o 0202-happy-number/happy-number.so 0202-happy-number/0202.c
0204:
	gcc $(CSHARED) -o 0204-count-primes/count-primes.so 0204-count-primes/0204.c
0242:
	gcc $(CSHARED) -o 0242-valid-anagram/valid-anagram.so 0242-valid-anagram/0242.c
0371:
	gcc $(CSHARED) -o 0371-sum-two-integers/sum-two-integers.so 0371-sum-two-integers/0371.c
0326:
	gcc $(CSHARED) -o 0326-power-of-three/power-of-three.so 0326-power-of-three/0326.c
0191:
	gcc $(CSHARED) -o 0191-number-1-bits/number-1-bits.so 0191-number-1-bits/0191.c
0231:
	gcc $(CSHARED) -o 0231-power-of-two/power-of-two.so 0231-power-of-two/0231.c
0342:
	gcc $(CSHARED) -o 0342-power-of-four/power-of-four.so 0342-power-of-four/0342.c
0007:
	gcc $(CSHARED) -o 0007-reverse-integer/reverse-integer.so 0007-reverse-integer/0007.c
0263:
	gcc $(CSHARED) -o 0263-ugly-number/ugly-number.so 0263-ugly-number/0263.c
0461:
	gcc $(CSHARED) -o 0461-hamming-distance/hamming-distance.so 0461-hamming-distance/0461.c
clean:
	rm -f 0344-reverse-string/reverse-string.so
	rm -f 1323-maximum-69-number/maximum-69-number.so
	rm -f 0136-single-number/single-number.so
	rm -f 0169-majority-element/majority-element.so
	rm -f 0283-move-zeroes/move-zeroes.so
	rm -f 0013-roman-to-integer/roman-to-integer.so
	rm -f 0202-happy-number/happy-number.so
	rm -f 0204-count-primes/count-primes.so
	rm -f 0242-valid-anagram/valid-anagram.so
	rm -f 0371-sum-two-integers/sum-two-integers.so
	rm -f 0326-power-of-three/power-of-three.so
	rm -f 0191-number-1-bits/number-1-bits.so
	rm -f 0231-power-of-two/power-of-two.so
	rm -f 0342-power-of-four/power-of-four.so
	rm -f 0007-reverse-integer/reverse-integer.so
	rm -f 0263-ugly-number/ugly-number.so
	rm -f 0461-hamming-distance/hamming-distance.so
